### ISSUE TITLE
Please adjust filestructure of Github

### ISSUE THREAD

**Issue by Bryantdl7** [myrage2000/ulogs#38]
Hello, currently your addon is inside a directory. This stops SVN clients for dynamically retrieving the latest files, as the addon ends up inside of another folder and becomes undetected. Please see https://github.com/TeamUlysses/utime for the appropriate format to be SVN friendly.

Thanks in advance!

**Comment by myrage2000** [comment]
Hi,
You wrote _"SVN clients"_, did you mean _git clients_ ?
I understand the issue. However, this is not a mistake and this format is much better for me.
If you have a server, you should write a .sh file to update your git clones, backup and copy the new files to /addons.

I cannot change the repository format (because I would have to remove everything and push a new request with everything again).
If ulogs2 is released in the future, I will format it like that.
